### ISSUE TITLE
There are unresovable dependencies around json_serializable

### ISSUE THREAD

**Issue by hoekbrwr** [MarcusNg/flutter_shopping_list#1]
I really am lost in the dependency forest of version numbers. The null safety addition does not help also. This renders the video unusable!

**Comment by MarcusNg** [comment]
Make sure you're on the `beta channel` as null safety isn't getting merged into `stable` until March 3.

Running `flutter pub get` with these package versions and environment is still working fine for me.
```
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.8.0-1.0.nullsafety.2
  firebase_auth: ^0.21.0-1.1.nullsafety.2
  cloud_firestore: ^0.17.0-1.0.nullsafety.2

  flutter_hooks: ^0.16.0-nullsafety.0
  hooks_riverpod: ^0.13.0-nullsafety.3

  freezed_annotation: ^0.13.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.1
```
